-- Cognera admin control tables.
-- Jalankan sekali di Supabase SQL Editor.

create table if not exists public.promos (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null default 'percent',
  value numeric not null default 0,
  max_uses integer,
  used_count integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  target text,
  link text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid,
  action text not null,
  table_name text,
  record_id text,
  created_at timestamptz not null default now()
);

alter table public.promos enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "admins manage promos" on public.promos;
create policy "admins manage promos" on public.promos for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins manage notifications" on public.notifications;
create policy "admins manage notifications" on public.notifications for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins manage audit logs" on public.audit_logs;
create policy "admins manage audit logs" on public.audit_logs for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));
